import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/main_data.dart';

class EarthquakeRequests{

  static Future<Autogenerated> GetAllEarthquakes() async {
    http.Response request = await http.get(
      Uri.https('everyearthquake.p.rapidapi.com','/earthquakes'),
  
      headers: {
       'X-RapidAPI-Key': 'c2e37fb2c5msh790db791cdf91e1p170e58jsn7492d3cf5815',
       'X-RapidAPI-Host': 'everyearthquake.p.rapidapi.com'
      });
  if (request.statusCode <= 299 && request.statusCode >= 200) {
   
    Autogenerated earthquakeResponse = Autogenerated.fromJson(json.decode(request.body));
    print(earthquakeResponse.data);

    return earthquakeResponse;
    
  } else {
    throw ('Request Fail');
  }
}
}