import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/main_data.dart';

class EarthquakeRequests{

  static Future<Autogenerated> GetAllEarthquakes() async {
    http.Response request = await http.get(
      Uri.https('everyearthquake.p.rapidapi.com','/earthquakes'),
  
      headers: {
       'X-RapidAPI-Key': 'b34e32e809mshc2b0fec98408538p1764e9jsnc6fcd43a5632',
       'X-RapidAPI-Host': 'everyearthquake.p.rapidapi.com'
      });
  if (request.statusCode <= 299 && request.statusCode >= 200) {
   
    Autogenerated earthquakeResponse = Autogenerated.fromJson(json.decode(request.body));
   
    print(request.body);
    return earthquakeResponse;
    
  } else {
    throw ('Request Fail');
  }
}
}